### ISSUE TITLE
Perf report while reading CZI file

### ISSUE THREAD

**Issue by snowformatics** [cgohlke/czifile#1]
Hello Christoph,

I have a question. Python is printing constantly this report while reading a CZI file:

`* Perf Report
***************************************************************************
Image Width = 1600, Height = 1200, total MegaPixels = 1.9 MP
m_ptEncDecPerf (excl I/O): 2475.000 milliseconds, 0.775758 MP/sec
*** WARNING: 360 time intervals were measured as zero. This perf timer has insufficient precision!
m_ptEndToEndPerf (incl I/O): 3303.000 milliseconds, 0.581290 MP/sec`

Do you have any idea what's all about this and how to supress this report?

Windows 10
Python 3.6
czifile 2019.7.2
Thanks again for your efforts with czifile,
S.

**Comment by cgohlke** [comment]
This is probably coming from the `jxrlib` library, which is used by `imagecodecs` for the `jpegxr` codec. Make sure jxrlib is compiled with `DISABLE_PERF_MEASUREMENT`.
