### ISSUE TITLE
timestamps?

### ISSUE THREAD

**Issue by horsto** [cgohlke/czifile#11]
Hi, I am trying to find timestamp information from my timelapse czi file. When I open the file through imagej I can find the ome metadata tree and timestamp info for every plane / image saved in the file. However, there seems to be no way to get there through czi file. 

I am attaching a screenshot of what the ome xml data extracted from the czi file looks like. What I want to access is the the `<Plane DeltaT... data`, but I just don't seem to be able to get there. 

<img width="1285" alt="Screenshot 2024-09-08 at 11 11 18" src="https://github.com/user-attachments/assets/4b8b6125-0ef2-4990-8408-da89207f60cc">

**Comment by cgohlke** [comment]
That information is probably in a "TimeStamps" attachment:

```Python
from czifile import CziFile

with CziFile(filename) as czi:
    for attachment in czi.attachments():
        if attachment.attachment_entry.name == 'TimeStamps':
            timestamps = attachment.data()
            break
    else:
        raise ValueError('TimeStamps not found')

print(timestamps)
print(round(timestamps[-1] - timestamps[0], 2))
```

**Comment by horsto** [comment]
Beautiful, thank you so much! That's it.

**Comment by cgohlke** [comment]
Czifile 2026.3.12 has a property to access the TimeStamps attachment data: `CziFile.timestamps`.

**Comment by horsto** [comment]
GREAT!
