### ISSUE TITLE
Suggestion: add a get_metadata function

### ISSUE THREAD

**Issue by amichaut** [cgohlke/czifile#3]
Very useful package! 
However, it would be extremely nice to be able to retrieve the identity of each image dimension. In this way, a get_metadata function could be used with the imread function so each dimension of the multidimensional image could be identified. 
Thanks!

**Comment by cgohlke** [comment]
That's what the `axes` attribute is for.

**Comment by amichaut** [comment]
Thanks for the reply. Maybe I missed it but I didn't find any documentation. So `axes` is an attribute of which object? `imread()` returns a ndarray which doesn't have any `axes` attribute

**Comment by cgohlke** [comment]
`axes` is an attribute of `CziFile` instances. Consider using [aicspylibczi](https://pypi.org/project/aicspylibczi/) which is actively maintained and better documented.

**Comment by amichaut** [comment]
okay thanks for the tip!
