### ISSUE TITLE
Convert .czi to .tif

### ISSUE THREAD

**Issue by yyyzzzhao** [cgohlke/czifile#4]
thanks for your great work. In my project, i want to process wsi image with an python-lib openslide, which support the .svs or .tif format. how can i convert .czi to .tif file by this lib? (it will be good if there are some code snippet)

**Comment by cgohlke** [comment]
Sorry, this library is focused on confocal imaging and does not currently handle multiple scenes or resolutions very well. 

Try Bio-Format's [bfconvert](https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/conversion.html) or [aicspylibczi](https://github.com/AllenCellModeling/aicspylibczi). 

I recommend to ask questions over at https://forum.image.sc/ .

**Comment by erikogabrielsson** [comment]
@cgohlke Can you elaborate what is missing in terms of multiple scenes and resolutions? When I load a pyramidal czi-file, I can read out the base layer with relative ease, but maybe Im missing something.

**Comment by cgohlke** [comment]
There is currently no high level support for scenes and pyramidal levels. The asarray function assembles all scenes and resolutions in one, potentially huge numpy array. You could of course iterate over and filter (by scene and pyramidal level) all DirectoryEntryDV yourself...
