### ISSUE TITLE
images with scenes greater than 0 cannot be processed

### ISSUE THREAD

**Issue by arielleleon** [cgohlke/czifile#5]
I am using czifile (2019.7.2) with python 3.6.12. I can easily read in stacked image files or single image files using czifile.imread as long as the scene in the header file is 0. 

Batch scans are now being collected on the Zeiss which include scanning multiple images as one file and then using the Zen software to split the scan into individual images. This process attaches a scene integer to each split image. The software collecting the images has not changed, just the imaging process.

Is there any way to get around this? 

For reference:
OS: Win10 v 1909
numpy==1.14
tifffile==2019.7.2
imagecodecs==2019.5.22

**Comment by cgohlke** [comment]
Czifile does not have a high level API to separate scenes. Either manually filter segments for Id or try [aicspylibczi](https://github.com/AllenCellModeling/aicspylibczi)/[aicsimageio](https://github.com/AllenCellModeling/aicsimageio).

**Comment by arielleleon** [comment]
I ran into the same issue with aicsimageio but I will see if I can figure out how to filter the scene. Thanks.

**Comment by cgohlke** [comment]
I'm not sure I correctly understood the issue. Maybe you could share the file(s).  Does Bio-Formats handle the file(s) correctly? Aicsimageio can use Bio-Formats as a backend. If no tool but Zen is able to read the files, maybe you can take the issue to [Image.sc](https://forum.image.sc/) where some ZEN, AICS, and Bio-Formats developers hang out.
