### ISSUE TITLE
problem with czi2tif

### ISSUE THREAD

**Issue by shenxiaochenn** [cgohlke/czifile#8]
When I use the czi2tif function, I find that the output of any image(wsi or czi file ) is black. I am confused about this and don't know what the reason is. thanks!

**Comment by cgohlke** [comment]
Could be that the [imagecodecs](https://pypi.org/project/imagecodecs/) package is not installed. Anyway, czifile is no longer maintained since many years and is known not to work well with WSI. Better use [pylibCZIrw](https://pypi.org/project/pylibCZIrw/).
